### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by Legoman99573** [Cl1608Ho/flarum-ext-discord-webhook#1]
I have set it up but when i make a thread, it wont post in the discord channel. Did i do something wrong with the configuration?

**Comment by Cl1608Ho** [comment]
You need to make sure the webhook URLs are correct and that you copied the URL into the right input (you have one input field for each tag, so you can lets say put only announcements on discord, or put them in a different channel).

**Comment by Legoman99573** [comment]
can you give me an example. I have never used webhooks till now.

**Comment by Legoman99573** [comment]
I see no documentation or a ReadMe.md file. May wanna add that ;)

**Comment by Cl1608Ho** [comment]
> I see no documentation or a ReadMe.md file. May wanna add that ;)

I never intended it to be used broadly, this is just for documentation and to let flarum devs help me.

You follow the tutorial that i linked in the settings panel (https://support.discordapp.com/hc/articles/228383668) (stop right before the github example), copy the url of the webhook and paste it under the name of the tag(s) you want it to appear.

**Comment by Legoman99573** [comment]
I receive a 400 BadRequest error in the php logs, but when I do it manually, I can see the JSON code. Idk if it's a host error over a ssh protocol =/

**Comment by Legoman99573** [comment]
*ssl

**Comment by Legoman99573** [comment]
Ok, i attempted to reinstall and got this:
`[thegearmc@cp flarum]$ composer require cl1608ho/flarum-ext-discord-webhook
Root package 'flarum/flarum' cannot require itself in its composer.json
Did you accidentally name your root package after an external package?
`

**Comment by Legoman99573** [comment]
It works, but i will make a suggestion in another post ;3
