### ISSUE TITLE
Suggestion: Add full URL to webhook

### ISSUE THREAD

**Issue by Legoman99573** [Cl1608Ho/flarum-ext-discord-webhook#2]
I know they look like this:
![image](https://cloud.githubusercontent.com/assets/7460704/22158522/37ce095e-df02-11e6-8df5-6f5b9c82ee7a.png)

But couldn't it show the full URL to say go there ;3

**Comment by Cl1608Ho** [comment]
Not really, because I use discord's embed api, and that provides options to link an URL or link an author, but it was their decision to do it this way.

**Comment by Legoman99573** [comment]
It was for a bit that hooks to a gaming server. It doesn't detect web links really well. Just asking ;3

**Comment by Legoman99573** [comment]
*for a plugin
