### ISSUE TITLE
Long forum threads won't get posted to Discord

### ISSUE THREAD

**Issue by Braintelligence** [Cl1608Ho/flarum-ext-discord-webhook#5]
I found out today that big forum threads do not trigger the webhook.
I guess you have a limit on the forum thread content for the webhook?

**Comment by Cl1608Ho** [comment]
Discord has a limitation of 2000 characters i think, and this plugin does not truncate articles longer than that.

Honestly,i haven't thought anyone is using this :)

**Comment by Braintelligence** [comment]
I use it for my guild which primarily uses Discord to ping whenever a new thread with the Discord subcategory is made. Is it possible for you to implement truncating? This would make this plug in feature-complete for me :).

**Comment by Cl1608Ho** [comment]
Committed, dunno what's necessary to put it on packagist or what that was.

**Comment by Braintelligence** [comment]
I'm using composer. Should work out-of-the-box right?

**Comment by Cl1608Ho** [comment]
Just did the release.... I guess that's it /shrug?
